### ISSUE TITLE
Shadowmetal Transmutation Research Unobtainable

### ISSUE THREAD

**Issue by Zsashas** [yorkeJohn/TAINTEDMAGIC-VERSION#2]
When clicked on, it says it added a research note to my inventory. However, no paper was consumed, and the chat shows the message "You lack the required knowledge to understand this".

I have infusion, metal transfusion, shadowmetal, and various other researches. I do not have the Eldritch tab unlocked yet. Is this supposed to be hidden until then? The Shadowmetal entry suggests this.

![image](https://cloud.githubusercontent.com/assets/6917535/11296197/8e1bf196-8f25-11e5-9390-47691368d63c.png)

**Comment by yorkeJohn** [comment]
Yes it should be hidden... There have been issues with research in the latest version. It will be fixed for the next.
